version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
  elasticsearch:
    image: 'elasticsearch:7.6.2'
    ports:
      - '9200:9200'
      - '9300:9300'
    container_name: 'elasticsearch'
    networks:
      - esnetwork
    environment:
      - discovery.type=single-node
  kibana:
    image: "kibana:7.6.2"
    ports:
      - '5601:5601'
    networks:
      - esnetwork
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  esnetwork: